### ISSUE TITLE
Bug in Internet Explorer 11

### ISSUE THREAD

**Issue by isabelle6** [algonquindesign-grads/2016#337]
The countdown timer doesn't work in Internet Explorer 11 on desktop. It replaces the numbers with NA.

![framework ie screenshot](https://cloud.githubusercontent.com/assets/6333962/13658582/799cf8aa-e646-11e5-91db-65afffd4fced.png)

**Comment by natalie-macpherson** [comment]
I'm really busy so I have not had time to make this fix. This is what we need to do in order to make the clock work in IE. If anybody has time to make the changes to the js files for the clock it would be great. If we are all overwhelm with our internships and we don't change it then it's all good it will just suck that it doesn't work in all browsers. Here is the link to the fix:

http://stackoverflow.com/questions/2182246/date-constructor-returns-nan-in-ie-but-works-in-firefox-and-chrome
